version: "1.0"

services:
  flask:
    build: .
    container_name: tripedia-flask
    environment:
      MONGO_URI: mongodb://mongo:27017/Tripedia
    ports:
      - "5858:5000"
    networks:
      - mongoDB
    restart: unless-stopped

networks:
  mongoDB:
    external: true
